Update CVE-2020-8908.json
google/cvelist pull request #1
Opened 2021-01-28 09:41 UTC by sirdarckcat

Please TAL @u269c.

After, we should send this to cpovirk and cgdecker and then to JLLeitschuh before merging to CVEProject/cvelist.

2021-01-28 18:45 UTC, nick-someone commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exist in all Guava versions allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guav
Here's an alternative draft, which might be a bit long.

A temp directory creation vulnerability exists in Guava, allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guava com.google.common.io.Files.createTempDir(). The permissions granted to the directory created default to the standard unix-like /tmp ones, leaving the files open. The method in question has been marked @Deprecated in versions 30.0 and later and should not be used. For Android developers, we recommend choosing a temporary directory API provided by Android, such as context.getCacheDir(). For other Java developers, we recommend migrating to the Java 7 API java.nio.file.Files.createTempDirectory() which explicitly configures permissions of 700, configuring the Java runtime's java.io.tmpdir system property to point to a location whose permissions are appropriately configured, or to explicitly change the permissions after the creation of the directory if neither are possible.

2021-01-28 23:11 UTC, cpovirk commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exist in all Guava versions allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guav
Two thoughts:

> The permissions granted to the directory created default

I think that section technically parses unambiguously to English, but I still slowed down a little to make sure I had it right.

> leaving the files open

Since "open" has another meaning in the context of files, we may want to find another word. I was going to say "world-readable," but that may sound like "readable remotely," which is of course false (and contrary to the previous sentence).

"By default, the created directory is readable by an attacker with access to the system's temporary directory?"

2021-01-28 23:13 UTC, cpovirk commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exist in all Guava versions allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guav
Sorry, one other comment:

> to explicitly change the permissions after the creation of the directory if neither are possible

We may want to explicitly note that that _shrinks_ the window, but, if the attacker gets in before the permissions change, the attacker can retain access even _after_ the permissions change.

2021-01-29 11:09 UTC, u269c commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exist in all Guava versions allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guav
LGTM

it is a bit longer than usual, but nothing alarming here. It is OK to provide good alternatives; I like it in general.

@sirdarckcat - please include this in your branch! thank you,

2021-01-29 11:19 UTC, sirdarckcat commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exist in all Guava versions allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guav
added. asked for a second opinion on the sentence. might edit it in a few hours

2021-01-29 12:33 UTC, sirdarckcat commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exist in all Guava versions allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guav
@sroettger:
>did you know that you can't open files securely in java?
>there is no api to open files without following symlinks in the path
>like openat()

updated the advisory to clear this up.

2021-01-29 12:34 UTC, sirdarckcat commented
@JLLeitschuh ptal

2021-01-29 13:52 UTC, JLLeitschuh commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exists in all versions of Guava, allowing an attacker with access to the machine to potentially access data in a temporary directory created by the
The only change I would recommend is offering a workaround option of setting the system property `java.io.tmpdir` to a "safe" directory.

2021-01-29 13:54 UTC, JLLeitschuh requested changes
Two minor changes

2021-01-29 13:54 UTC, JLLeitschuh commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exists in all versions of Guava, allowing an attacker with access to the machine to potentially access data in a temporary directory created by the
I might also change this: 

> By default, the created directory is world-readable (readable by an attacker with access to the system).

To be something like:

> By default, on unix-like systems (and very old versions of MacOS), the created directory is world-readable (readable by an attacker with access to the system)

2021-01-29 14:01 UTC, JLLeitschuh commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exists in all versions of Guava, allowing an attacker with access to the machine to potentially access data in a temporary directory created by the
The "very old versions of MacOS" came from this other vulnerability I found in Apache Groovy.
I didn't write the "very old versions of MacOS" line, I'm guessing someone in the Apache foundation did that research and put that in there.

So, I can't back up that fact, but I could send an email if someone feels that that's important to verify.

http://groovy-lang.org/security.html#CVE-2020-17521

2021-01-29 16:03 UTC, cpovirk commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exist in all Guava versions allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guav
I'm not sure if what I'm about to say ends up being relevant in this specific case, but: Java does support a relative-path, no-symlink-following `openat` as of Java 7+. But you have to go out of your way to get at it:

```
$ cat SecureOpenAt.java
import static java.nio.file.LinkOption.NOFOLLOW_LINKS;
import static java.nio.file.StandardOpenOption.READ;
import static java.util.Arrays.asList;

import java.nio.file.*;
import java.util.HashSet;

class SecureOpenAt {
  public static void main(String[] args) throws Exception {
    SecureDirectoryStream<Path> stream =
        (SecureDirectoryStream<Path>) Files.newDirectoryStream(Paths.get("/tmp/dir"));
    Path path = stream.iterator().next();
    stream.newByteChannel(path.getFileName(), new HashSet<>(asList(READ, NOFOLLOW_LINKS)));
  }
}

$ rm -rf /tmp/dir && mkdir /tmp/dir && touch /tmp/dir/file && javac SecureOpenAt.java && strace -f -e openat java SecureOpenAt 2>&1 | grep -e '"/tmp/dir"' -e '"file"'
[pid 425601] openat(AT_FDCWD, "/tmp/dir", O_RDONLY) = 4
[pid 425601] openat(5, "file", O_RDONLY|O_NOFOLLOW) = 6
```

(Guava uses this in [`MoreFiles.deleteRecursively`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/io/MoreFiles.html#deleteRecursively-java.nio.file.Path-com.google.common.io.RecursiveDeleteOption...-).)

2021-01-29 16:41 UTC, sirdarckcat commented on 2020/8xxx/CVE-2020-8908.json
> +		"value": "A temp directory creation vulnerability exists in all versions of Guava, allowing an attacker with access to the machine to potentially access data in a temporary directory created by the
> The only change I would recommend is offering a workaround option of setting the system property `java.io.tmpdir` to a "safe" directory.

It already mentions that, I think `[[or]] configuring the Java runtime's java.io.tmpdir system property to point to a location whose permissions are appropriately configured` - it's just missing an or.

2021-01-29 16:44 UTC, sirdarckcat commented
done, @u269c plz be merging! ;)

2021-01-29 16:45 UTC, merged

2021-01-29 17:11 UTC, JLLeitschuh reviewed
LGTM! Thanks!

2021-02-04 14:53 UTC, pauldevt commented
The change is never going to reach mitre (due to the way it was done + how mitre handles downstream changes).
So I'm going to revert this and submit the PR directly to Mitre (I'll CC you Justin) but its just shuffling paper. The wording changes will still be the same.

2021-02-04 15:04 UTC, pauldevt commented
Ok that went smoother than thought https://github.com/CVEProject/cvelist/pull/713 should do the trick. Should be accepted shortly.

2021-02-05 22:43 UTC, nick-someone commented
Thanks for pushing this through @pauldevt!